import esbuild from "esbuild";
import process from "process";

// Node builtins kept external (provided by Electron at runtime). Inlined
// here to avoid the (deprecated) `builtin-modules` dependency.
const builtins = [
  "assert", "async_hooks", "buffer", "child_process", "cluster", "console",
  "constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
  "events", "fs", "http", "http2", "https", "inspector", "module", "net",
  "os", "path", "perf_hooks", "process", "punycode", "querystring", "readline",
  "repl", "stream", "string_decoder", "sys", "timers", "tls", "trace_events",
  "tty", "url", "util", "v8", "vm", "wasi", "worker_threads", "zlib",
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/ledokter/obsidian-mega-sync
MIT License - Copyright (c) ledokter
*/`;

const prod = process.argv[2] === "production";

const commonOptions = {
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  platform: "node",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  banner: { js: banner },
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
};

if (prod) {
  await esbuild.build(commonOptions);
  console.log("Build complete (production).");
} else {
  const context = await esbuild.context(commonOptions);
  await context.watch();
  console.log("Watching for changes...");
}