import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/ledokter/obsidian-mega-sync
MIT License - Copyright (c) ledokter
*/`;

const prod = process.argv[2] === "production";

const commonOptions = {
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  platform: "node",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  banner: { js: banner },
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
};

if (prod) {
  await esbuild.build(commonOptions);
  console.log("Build complete (production).");
} else {
  const context = await esbuild.context(commonOptions);
  await context.watch();
  console.log("Watching for changes...");
}